repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: a27a2e47c7751b639d2b5badf0ef6ff11fee893f  # frozen: v0.15.4
    hooks:
      - id: ruff
        exclude: ^corp-
      - id: ruff-format
        exclude: ^corp-

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: ^corp-
      - id: end-of-file-fixer
        exclude: ^corp-
      - id: file-contents-sorter
        files: '^fuzz_targets.txt$'
      - id: trailing-whitespace
        exclude: ^corp-

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: b546b77c44c466a54a42af5499dcc0dcc1a3193f  # frozen: v1.22.0
    hooks:
      - id: zizmor
        args: [--fix=all]
