name: Build

permissions: {}

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - address
          # - memory  Too slow for CI
          - undefined

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          # Temporary, for testing use my branch with the updated build scripts.
          repository: stanfromireland/oss-fuzz
          ref: merge-cpython3-python3-libraries
          path: oss-fuzz
          persist-credentials: false

      - name: Patch Dockerfile to use this ref
        run: |
          sed -i "s|git clone --depth 1 --branch main https://github.com/python/library-fuzzers.git|git clone --depth 1 --branch ${BRANCH} ${CLONE_URL} library-fuzzers|" \
            oss-fuzz/projects/python3-libraries/Dockerfile
        env:
          BRANCH: ${{ github.head_ref }}
          CLONE_URL: ${{ github.event.pull_request.head.repo.clone_url }}

      - name: Build fuzzers
        run: |
          cd oss-fuzz
          python infra/helper.py build_fuzzers python3-libraries \
            --engine libfuzzer \
            --sanitizer ${{ matrix.sanitizer }} \
            --architecture x86_64

      - name: Check build
        run: |
          cd oss-fuzz
          python infra/helper.py check_build python3-libraries \
            --engine libfuzzer \
            --sanitizer ${{ matrix.sanitizer }} \
            --architecture x86_64 \
            -e ALLOWED_BROKEN_TARGETS_PERCENTAGE=0
